### ISSUE TITLE
WebSocket connection error when trying to submit transaction 

### ISSUE THREAD

**Issue by mattxsmith** [AugurProject/augur-app#114]
The app works fine, up until I try to submit or cancel an order using Metamask. No errors show up in the UI or in the console, the transaction just never gets sent to the network. I'm connecting to my geth node running with the following settings:

`geth console --rpc --ws --syncmode "light" --rpcaddr "0.0.0.0" --wsaddr "0.0.0.0" --rpccorsdomain "*" --wsorigins "*"`

Here are the errors from the Augur node logs.

`[2018-07-10 19:51:25.966] [error] getter error:  Error: Unable to acquire a connection
    at Client_SQLite3.acquireConnection (/Applications/augur.app/Contents/Resources/app/node_modules/augur-node/node_modules/knex/lib/client.js:318:40)
    at Runner.ensureConnection (/Applications/augur.app/Contents/Resources/app/node_modules/augur-node/node_modules/knex/lib/runner.js:227:24)
    at Runner.run (/Applications/augur.app/Contents/Resources/app/node_modules/augur-node/node_modules/knex/lib/runner.js:47:42)
    at Builder.Target.then (/Applications/augur.app/Contents/Resources/app/node_modules/augur-node/node_modules/knex/lib/interface.js:35:43)
    at Builder.Target.(anonymous function) [as asCallback] (/Applications/augur.app/Contents/Resources/app/node_modules/augur-node/node_modules/knex/lib/interface.js:85:26)
    at Object.getMarketPriceCandlesticks (/Applications/augur.app/Contents/Resources/app/node_modules/augur-node/build/server/getters/get-market-price-candlesticks.js:24:11)
    at Object.dispatchJsonRpcRequest (/Applications/augur.app/Contents/Resources/app/node_modules/augur-node/build/server/dispatch-json-rpc-request.js:53:52)
    at WebSocket.websocket.on (/Applications/augur.app/Contents/Resources/app/node_modules/augur-node/build/server/run-websocket-server.js:81:53)
    at emitOne (events.js:116:13)
    at WebSocket.emit (events.js:211:7)
    at Receiver.receiverOnMessage (/Applications/augur.app/Contents/Resources/app/node_modules/ws/lib/websocket.js:718:20)
    at emitOne (events.js:116:13)
    at Receiver.emit (events.js:211:7)
    at Receiver.dataMessage (/Applications/augur.app/Contents/Resources/app/node_modules/ws/lib/receiver.js:414:14)
    at Receiver.getData (/Applications/augur.app/Contents/Resources/app/node_modules/ws/lib/receiver.js:346:17)
    at Receiver.startLoop (/Applications/augur.app/Contents/Resources/app/node_modules/ws/lib/receiver.js:133:22)
`

**Comment by mattxsmith** [comment]
This issue was fixed using Edge instead of Metamask. Closing because I don't think there error message provided is the correct logging for this issue.
