### ISSUE TITLE
Failed to startup: [object Object]

### ISSUE THREAD

**Issue by timnugent** [AugurProject/augur-app#121]
Ubuntu 16.04, v1.0.2. After 5 mins of syncing (before starting the Augur App), I get this every second:

[11:10:39.155] [info] Failed to startup: [object Object]
[11:10:40.153] [error] TimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at /opt/augur/resources/app.asar/node_modules/augur-node/node_modules/knex/lib/client.js:326:13
    at tryCatcher (/opt/augur/resources/app.asar/node_modules/bluebird/js/release/util.js:16:23)
    at /opt/augur/resources/app.asar/node_modules/bluebird/js/release/catch_filter.js:17:41
    at tryCatcher (/opt/augur/resources/app.asar/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/opt/augur/resources/app.asar/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/opt/augur/resources/app.asar/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/opt/augur/resources/app.asar/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/opt/augur/resources/app.asar/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/opt/augur/resources/app.asar/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/opt/augur/resources/app.asar/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/opt/augur/resources/app.asar/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)

"Failed to startup: [object Object]" flashes up in the frontend

Looks like this issue:
https://github.com/tgriesser/knex/issues/2302

**Comment by petervecchiarelli** [comment]
https://app.clubhouse.io/augur/story/13777/github-failed-to-startup-object-object

**Comment by timnugent** [comment]
Still getting this with 1.0.3

**Comment by page1** [comment]
Just spotted this on my 1.0.3. Restarting app to see if things improve.

**Comment by sharkcrayon** [comment]
@timnugent @page1 Are you still getting this with v1.0.4?

**Comment by timnugent** [comment]
Just did a sync with 1.0.4 and didn't see it, you can probably close this

**Comment by page1** [comment]
@sharkcrayon Have not run into this on 1.0.4

**Comment by bthaile** [comment]
@timnugent @page1 Checking in again, have y'all seen this issue, ` Failed to startup: [object Object]`?

**Comment by bthaile** [comment]
Also, 1.0.5 has data stability fixes as well. I’ll close this for now. Thanks

**Comment by page1** [comment]
@bthaile Seeing these come back in 1.0.5

```
[2018-07-22 22:43:00.590] [error] TimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at /Applications/Augur.app/Contents/Resources/app/node_modules/augur-node/node_modules/knex/lib/client.js:326:13
    at tryCatcher (/Applications/Augur.app/Contents/Resources/app/node_modules/bluebird/js/release/util.js:16:23)
    at /Applications/Augur.app/Contents/Resources/app/node_modules/bluebird/js/release/catch_filter.js:17:41
    at tryCatcher (/Applications/Augur.app/Contents/Resources/app/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Applications/Augur.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Applications/Augur.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Applications/Augur.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Applications/Augur.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/Applications/Augur.app/Contents/Resources/app/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Applications/Augur.app/Contents/Resources/app/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Applications/Augur.app/Contents/Resources/app/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
```

**Comment by bthaile** [comment]
Seems like your augur-node is getting flooded with requests. We had that issue with dispute market view in past versions. Currently augur-node is setup to have only 1 sql connection. 

Not sure what would cause multiple connections to sqlite3 db. or could be that multiple transactions are getting created before the initial transaction had time to close. 

Can you describe the activities you were trying to preform when this occurred?

**Comment by page1** [comment]
Not sure exactly what I was doing. You said 1 sql connection, would opening multiple tabs to Augur breach this limit?

Everything I do is by hand in Chrome, generally signed in with a ledger. Checking markets sometimes by making new tabs to find out if there are any interesting bids/asks.

**Comment by timnugent** [comment]
Just seen this again in 1.0.6

App was still syncing, didn't have the UI open in a web browser:

[17:08:15.258] [info] new block: 6011947, 1532292545 (Sun Jul 22 2018 21:49:05 GMT+0100 (BST))
[17:08:15.261] [info] Processing 1 logs
[17:08:15.268] [info] new block: 6011950, 1532292588 (Sun Jul 22 2018 21:49:48 GMT+0100 (BST))
[17:08:15.271] [info] Processing 8 logs
websocket wss://mainnet.infura.io/ws closed: 1006 Connection dropped by remote peer.
websocket wss://mainnet.infura.io/ws opened
[17:13:15.400] [error] TimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at /opt/Augur/resources/app.asar/node_modules/augur-node/node_modules/knex/lib/client.js:326:13
    at tryCatcher (/opt/Augur/resources/app.asar/node_modules/bluebird/js/release/util.js:16:23)
    at /opt/Augur/resources/app.asar/node_modules/bluebird/js/release/catch_filter.js:17:41
    at tryCatcher (/opt/Augur/resources/app.asar/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/opt/Augur/resources/app.asar/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/opt/Augur/resources/app.asar/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/opt/Augur/resources/app.asar/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/opt/Augur/resources/app.asar/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/opt/Augur/resources/app.asar/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/opt/Augur/resources/app.asar/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/opt/Augur/resources/app.asar/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)

**Comment by page1** [comment]
I was having weird things going on such as loading the market page and seeing no markets so I reset the db. Sync has not been smooth. Currently seeing a bunch of these after not looking for over an hour.

```
[2018-07-31 13:45:24.917] [error] TimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at /Applications/Augur.app/Contents/Resources/app/node_modules/augur-node/node_modules/knex/lib/client.js:326:13
    at tryCatcher (/Applications/Augur.app/Contents/Resources/app/node_modules/bluebird/js/release/util.js:16:23)
    at /Applications/Augur.app/Contents/Resources/app/node_modules/bluebird/js/release/catch_filter.js:17:41
    at tryCatcher (/Applications/Augur.app/Contents/Resources/app/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Applications/Augur.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Applications/Augur.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Applications/Augur.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Applications/Augur.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/Applications/Augur.app/Contents/Resources/app/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Applications/Augur.app/Contents/Resources/app/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Applications/Augur.app/Contents/Resources/app/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
```

Going to restart sync and hope to get farther.

**Comment by adrake33** [comment]
@timnugent @page1 Are either of you still having issues as of version 1.5.0? Can this be closed?

**Comment by adrake33** [comment]
Closing this issue for now. Feel free to reopen if need be.
