### ISSUE TITLE
Error: SQLITE_CONSTRAINT (positiveEndTime)

### ISSUE THREAD

**Issue by timnugent** [AugurProject/augur-app#124]
Ubuntu 16.04, v1.0.2, crashes like this:

[12:55:17.740] [info] 
[12:55:18.740] [info] 
new block: 5944595 1531310192
[12:55:19.534] [info] new block: 5944595 1531310192
Processing 12 logs
[12:55:19.537] [info] Processing 12 logs
Fatal Error, shutting down servers { Error: SQLITE_CONSTRAINT: CHECK constraint failed: positiveEndTime errno: 19, code: 'SQLITE_CONSTRAINT' }
[12:55:21.225] [error] Fatal Error, shutting down servers Error: SQLITE_CONSTRAINT: CHECK constraint failed: positiveEndTime

[12:55:21.225] [error] Error: SQLITE_CONSTRAINT: CHECK constraint failed: positiveEndTime

[12:55:21.241] [info] Stopping Augur Node Server
Stopping Augur Node Server
[12:55:21.242] [info] Stopping Augur Node Server
[12:55:21.242] [info] Stopping Augur UI Server
[12:55:21.243] [info] Failed to startup: insert into `markets` (`category`, `creationBlockNumber`, `creationFee`, `designatedReportStake`, `designatedReporter`, `endTime`, `feeWindow`, `finalizationBlockNumber`, `forking`, `initialReportSize`, `longDescription`, `marketCreator`, `marketCreatorFeeRate`, `marketCreatorFeesBalance`, `marketCreatorMailbox`, `marketCreatorMailboxOwner`, `marketId`, `marketStateId`, `marketType`, `maxPrice`, `minPrice`, `needsDisavowal`, `needsMigration`, `numOutcomes`, `numTicks`, `reportingFeeRate`, `resolutionSource`, `scalarDenomination`, `sharesOutstanding`, `shortDescription`, `tag1`, `tag2`, `universe`, `volume`) values ('CRYPTOCURRENCIES', 5944595, '0.01', '0.349680582682291667', '0x2404a39e447d0c8b417049fc42b468a26990b4cc', 0, '0x0000000000000000000000000000000000000000', NULL, 0, NULL, 'As reported by major exchanges.', '0x2404a39e447d0c8b417049fc42b468a26990b4cc', '0.01', '0', '0xf0665f59e0430993e334abe3d818da6bad39a444', '0x2404a39e447d0c8b417049fc42b468a26990b4cc', '0x4e0ee58bf4230d3b799584e1a6027b4bda9fc4ed', 143, 'yesNo', '1', '0', 0, 0, 2, '10000', '0.01', 'https://coinmarketcap.com/currencies/augur/', NULL, '0', 'Will REP token trade above $32 at the end of 2018?', 'AUGUR', 'REP', '0xe991247b78f937d7b69cfc00f1a487a293557677', '0') - SQLITE_CONSTRAINT: CHECK constraint failed: positiveEndTime
Unhandled rejection Error: SQLITE_CONSTRAINT: CHECK constraint failed: positiveEndTime

[12:55:21.250] [error] Error: aborted
    at PendingOperation.abort (/opt/augur/resources/app.asar/node_modules/tarn/lib/PendingOperation.js:25:17)
    at Promise.all.pendingAcquires.map.acquire (/opt/augur/resources/app.asar/node_modules/tarn/lib/Pool.js:190:23)
    at Array.map (<anonymous>)
    at Promise.all.then.then (/opt/augur/resources/app.asar/node_modules/tarn/lib/Pool.js:189:34)
    at <anonymous>

[12:55:21.250] [error] Error: aborted
    at PendingOperation.abort (/opt/augur/resources/app.asar/node_modules/tarn/lib/PendingOperation.js:25:17)
    at Promise.all.pendingAcquires.map.acquire (/opt/augur/resources/app.asar/node_modules/tarn/lib/Pool.js:190:23)
    at Array.map (<anonymous>)
    at Promise.all.then.then (/opt/augur/resources/app.asar/node_modules/tarn/lib/Pool.js:189:34)
    at <anonymous>

(node:19211) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 5): Error: Object has been destroyed
(node:19211) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:19211) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 6): Error: Object has been destroyed

**Comment by timnugent** [comment]
Similar crash, this time with nonnegativeBalance:

[17:00:31.138] [info] 
new block: 5951579 1531410684
[17:00:31.142] [info] new block: 5951579 1531410684
new block: 5951580 1531410689
[17:00:31.152] [info] new block: 5951580 1531410689
Processing 1 logs
[17:00:31.160] [info] Processing 1 logs
Fatal Error, shutting down servers { Error: SQLITE_CONSTRAINT: CHECK constraint failed: nonnegativeBalance errno: 19, code: 'SQLITE_CONSTRAINT' }
[17:00:31.164] [error] Fatal Error, shutting down servers Error: SQLITE_CONSTRAINT: CHECK constraint failed: nonnegativeBalance

[17:00:31.165] [error] Error: SQLITE_CONSTRAINT: CHECK constraint failed: nonnegativeBalance

[17:00:31.184] [info] Stopping Augur Node Server
Stopping Augur Node Server
[17:00:31.185] [info] Stopping Augur Node Server
[17:00:31.185] [info] Stopping Augur UI Server
[17:00:31.186] [info] Failed to startup: update `balances` set `balance` = '-4990000000000000000' where `token` = '0x1985365e9f78359a9b6ad760e32412f4a445e862' and `owner` = '0xc3b3190a055c283c0c31998d360c6a950b5d8fb9' - SQLITE_CONSTRAINT: CHECK constraint failed: nonnegativeBalance
Unhandled rejection Error: SQLITE_CONSTRAINT: CHECK constraint failed: nonnegativeBalance

**Comment by petervecchiarelli** [comment]
https://app.clubhouse.io/augur/story/13779/github-error-sqlite-constraint-positiveendtime

**Comment by nuevoalex** [comment]
@timnugent Could you update the app to version 1.0.3 and see if you still get this error?
