### ISSUE TITLE
JavaScript error: Websocket is not open 

### ISSUE THREAD

**Issue by page1** [AugurProject/augur-app#131]
Just random error on Mac
```
Uncaught Exception:
Error: WebSocket is not open: readyState 2 (CLOSING)
    at WebSocket.ping (/Applications/augur.app/Contents/Resources/app/node_modules/ws/lib/websocket.js:249:19)
    at Timeout.timers_1.setInterval [as _onTimeout] (/Applications/augur.app/Contents/Resources/app/node_modules/augur-node/build/server/run-websocket-server.js:51:71)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
```

<img width="895" alt="screen shot 2018-07-11 at 11 40 57 am" src="https://user-images.githubusercontent.com/6609556/42589761-52d90a06-84ff-11e8-8cbb-a15fbea2112a.png">

**Comment by bthaile** [comment]
https://app.clubhouse.io/augur/story/13829/need-to-catch-websocket-errors

**Comment by sharkcrayon** [comment]
@page1 Are you still seeing this with 1.0.7?

**Comment by sharkcrayon** [comment]
This should be fixed now based on @epheph's PR. Closing, but please let us know if you see this again.
