### ISSUE TITLE
Could not find balance for token decrease

### ISSUE THREAD

**Issue by timnugent** [AugurProject/augur-app#146]
Ubuntu 16.04, v1.0.2, crashes like this:

[17:17:29.803] [info] Stopping Augur Node Server
Stopping Augur Node Server
[17:17:29.804] [info] Stopping Augur Node Server
[17:17:29.804] [info] Stopping Augur UI Server
[17:17:29.805] [info] Failed to startup: Could not find balance for token decrease (token: 0x1985365e9f78359a9b6ad760e32412f4a445e862, owner: 0x81a5415d07cfe64e11ebe5d5b6bd576c46d8d931)
Unhandled rejection Error: Could not find balance for token decrease (token: 0x1985365e9f78359a9b6ad760e32412f4a445e862, owner: 0x81a5415d07cfe64e11ebe5d5b6bd576c46d8d931)
    at db.first.from.where.asCallback (/opt/augur/resources/app.asar/node_modules/augur-node/build/blockchain/log-processors/token/decrease-token-balance.js:13:29)
    at tryCatcher (/opt/augur/resources/app.asar/node_modules/bluebird/js/release/util.js:16:23)
    at Promise.successAdapter [as _fulfillmentHandler0] (/opt/augur/resources/app.asar/node_modules/bluebird/js/release/nodeify.js:22:30)
    at Promise._settlePromise (/opt/augur/resources/app.asar/node_modules/bluebird/js/release/promise.js:566:21)
    at Promise._settlePromise0 (/opt/augur/resources/app.asar/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/opt/augur/resources/app.asar/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/opt/augur/resources/app.asar/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/opt/augur/resources/app.asar/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/opt/augur/resources/app.asar/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)

**Comment by bthaile** [comment]
Doenload version 1.0.3. The syncing is more rebust.

**Comment by SirLancelot-OG** [comment]
Having the same issue using the latest augur-node software:

``Could not find balance for token decrease (token: 0x1985365e9f78359a9b6ad760e32412f4a445e862, owner: 0x4161e7eada1cd4047a2b68a0d7d539b5d54f1762)``

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'start' ]
2 info using npm@5.6.0
3 info using node@v8.11.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle augur-node@5.6.1~prestart: augur-node@5.6.1
6 info lifecycle augur-node@5.6.1~start: augur-node@5.6.1
7 verbose lifecycle augur-node@5.6.1~start: unsafe-perm in lifecycle true
8 verbose lifecycle augur-node@5.6.1~start: PATH: /usr/lib/node_modules/npm/nod$
9 verbose lifecycle augur-node@5.6.1~start: CWD: /opt/augur-node
10 silly lifecycle augur-node@5.6.1~start: Args: [ '-c', 'node ./build/runServe$
11 silly lifecycle augur-node@5.6.1~start: Returned: code: 1  signal: null
12 info lifecycle augur-node@5.6.1~start: Failed to exec start script
13 verbose stack Error: augur-node@5.6.1 start: `node ./build/runServer`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/nod$
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/nod$
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_pro$
14 verbose pkgid augur-node@5.6.1
15 verbose cwd /opt/augur-node
16 verbose Linux 4.15.0-32-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "start"
18 verbose node v8.11.3
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error augur-node@5.6.1 start: `node ./build/runServer`
22 error Exit status 1
23 error Failed at the augur-node@5.6.1 start script.
23 error This is probably not a problem with npm. There is likely additional lo$
24 verbose exit [ 1, true ]
```

**Comment by PichlerD** [comment]
Same issue on, 1.4 trying to use a current local parity node that has worked before. OS: Win10

**Comment by bthaile** [comment]
What ethereum node endpoint are you trying to connect to? 

There has been recent discoveries with parity. There’s a bug that doesn’t work well with Augur and the ethereum node needs specific start up parameters.
