### ISSUE TITLE
Fatal Error, shutting down servers Error: market and outcome not found for shareToken

### ISSUE THREAD

**Issue by TacoByte** [AugurProject/augur-app#158]
1.0.3

The app was humming along 4 blocks behind. Then I noticed it had fallen behind around 250 blocks and seemed to be stuck there. That lasted a couple minutes, then it crash quit. 

```
[2018-07-13 11:27:55.828] [info] new block: 5955772 1531471192
[2018-07-13 11:27:55.838] [info] new block: 5955773 1531471213
[2018-07-13 11:27:55.847] [info] new block: 5955774 1531471216
[2018-07-13 11:27:55.855] [info] Processing 3 logs
[2018-07-13 11:27:55.873] [error] Fatal Error, shutting down servers Error: market and outcome not found for shareToken 0xf312311f14d93678880ff9a4f4eef1779291a178 (0x5bf0e2be5daab92183625891b2f1b12f5c229d80018bfb6c9785e64fdba9c0e1
    at db.first.from.where.asCallback (/Applications/augur.app/Contents/Resources/app/node_modules/augur-node/build/blockchain/log-processors/order-created.js:20:29)
    at tryCatcher (/Applications/augur.app/Contents/Resources/app/node_modules/bluebird/js/release/util.js:16:23)
    at Promise.successAdapter [as _fulfillmentHandler0] (/Applications/augur.app/Contents/Resources/app/node_modules/bluebird/js/release/nodeify.js:22:30)
    at Promise._settlePromise (/Applications/augur.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:566:21)
    at Promise._settlePromise0 (/Applications/augur.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Applications/augur.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Applications/augur.app/Contents/Resources/app/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Applications/augur.app/Contents/Resources/app/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Applications/augur.app/Contents/Resources/app/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)

[2018-07-13 11:27:55.874] [error] Error: market and outcome not found for shareToken 0xf312311f14d93678880ff9a4f4eef1779291a178 (0x5bf0e2be5daab92183625891b2f1b12f5c229d80018bfb6c9785e64fdba9c0e1
    at db.first.from.where.asCallback (/Applications/augur.app/Contents/Resources/app/node_modules/augur-node/build/blockchain/log-processors/order-created.js:20:29)
    at tryCatcher (/Applications/augur.app/Contents/Resources/app/node_modules/bluebird/js/release/util.js:16:23)
    at Promise.successAdapter [as _fulfillmentHandler0] (/Applications/augur.app/Contents/Resources/app/node_modules/bluebird/js/release/nodeify.js:22:30)
    at Promise._settlePromise (/Applications/augur.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:566:21)
    at Promise._settlePromise0 (/Applications/augur.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Applications/augur.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Applications/augur.app/Contents/Resources/app/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Applications/augur.app/Contents/Resources/app/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Applications/augur.app/Contents/Resources/app/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)

[2018-07-13 11:27:55.888] [info] Stopping Augur Node Server
[2018-07-13 11:27:55.889] [info] Stopping Augur Node Server
[2018-07-13 11:27:55.891] [info] Stopping Augur UI Server
```

**Comment by justinbarry** [comment]
@TacoByte Did this happen just after your machine woke up from sleep?

**Comment by TacoByte** [comment]
@justinbarry No, just randomly

**Comment by petervecchiarelli** [comment]
https://app.clubhouse.io/augur/story/14117/github-fatal-error-shutting-down-servers-error-market-and-outcome-not-found-for-sharetoken

**Comment by sharkcrayon** [comment]
@page1 @TacoByte Are you seeing this with the latest app (v1.0.5)?

**Comment by page1** [comment]
@sharkcrayon Haven't seen this so far with 1.0.5
