### ISSUE TITLE
Error: Received log for block hash 0xabc when asking for logs of block 0xdef

### ISSUE THREAD

**Issue by timnugent** [AugurProject/augur-app#176]
Ubuntu 16.04, 1.0.3:

Error: Received log for block hash 0xa15f139497b384070477103ddada406a61ed0c2b27ec54cbd4a6b455fb47d6e4 when asking for logs of block 0x4d0f94ac8ba0b9c06113d662b36faf7ffe42c41e598a09658fd7ab98ab1ba757.
    at /opt/augur/resources/app.asar/node_modules/augur-blockstream/output/source/log-reconciler.js:154:19
    at Array.forEach (<anonymous>)
    at ensureBlockhash (/opt/augur/resources/app.asar/node_modules/augur-blockstream/output/source/log-reconciler.js:152:10)
    at Object.<anonymous> (/opt/augur/resources/app.asar/node_modules/augur-blockstream/output/source/log-reconciler.js:52:21)
    at step (/opt/augur/resources/app.asar/node_modules/augur-blockstream/output/source/log-reconciler.js:32:23)
    at Object.next (/opt/augur/resources/app.asar/node_modules/augur-blockstream/output/source/log-reconciler.js:13:53)
    at fulfilled (/opt/augur/resources/app.asar/node_modules/augur-blockstream/output/source/log-reconciler.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by petervecchiarelli** [comment]
https://app.clubhouse.io/augur/story/14201/github-error-received-log-for-block-hash-0xabc-when-asking-for-logs-of-block-0xdef

**Comment by epheph** [comment]
@timnugent this error was not fatal for you, right? This should be classified as a warning. There is a problem with the ethereum protocol (that will be fixed in EIP-234), this message notes that the "block stream" noticed the error, but it knows how to deal with it.

We should change the message to seem more informative, perhaps noting that it is "info".

**Comment by timnugent** [comment]
Yes, this one was fatal for me

**Comment by adrake33** [comment]
Closing since EIP-234 has been merged into geth/parity.
