### ISSUE TITLE
Augur app crashes when syncing

### ISSUE THREAD

**Issue by joeykrug** [AugurProject/augur-app#210]
```
[08:08:53.727] [info] /Users/joeykrug2/Library/Application Support/augur/augur-1-syncing-2.db
[08:08:53.923] [info] Getting Augur logs from block 5926223 to block 5998670
got 389 logs in blocks { fromBlock: 5926223, toBlock: 5929549 }


#
# Fatal error in , line 0
# API fatal error handler returned after process out of memory
#
Illegal instruction: 4
```

**Comment by joeykrug** [comment]
Restarted it, got this:

```
[08:11:11.572] [info] Getting Augur logs from block 5926223 to block 5998677
got 390 logs in blocks { fromBlock: 5926223, toBlock: 5929556 }
{ Error: Unexpectedly received a message from the transport that was not an object
    at /Applications/augur.app/Contents/Resources/app/node_modules/ethrpc/src/rpc/blockchain-message-handler.js:19:54
    at store.dispatch (/Applications/augur.app/Contents/Resources/app/node_modules/redux-thunk-subscribe/src/index.js:10:18)
    at Object.<anonymous> (/Applications/augur.app/Contents/Resources/app/node_modules/ethrpc/src/reset-state.js:45:9)
    at HttpTransport.<anonymous> (/Applications/augur.app/Contents/Resources/app/node_modules/ethrpc/src/transport/http-transport.js:54:12)
    at Request.self.callback (/Applications/augur.app/Contents/Resources/app/node_modules/request/request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/Applications/augur.app/Contents/Resources/app/node_modules/request/request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/Applications/augur.app/Contents/Resources/app/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
  '0': '{',
  '1': '"',
  '2': 'j',
  '3': 's',
  '4': 'o',
  '5': 'n',
  '6': 'r',
  '7': 'p',
  '8': 'c',
  '9': '"',
  '10': ':',
  '11': '"',
  '12': '2',
  '13': '.',
  '14': '0',
  '15': '"',
  '16': ',',
  '17': '"',
  '18': 'i',
  '19': 'd',
  '20': '"',
  '21': ':',
  '22': '5',
  '23': ',',
  '24': '"',
  '25': 'r',
  '26': 'e',
  '27': 's',
  '28': 'u',
  '29': 'l',
  '30': 't',
  '31': '"',
  '32': ':',
  '33': '[',
  '34': '{',
  '35': '"',
  '36': 'a',
  '37': 'd',
  '38': 'd',
  '39': 'r',
  '40': 'e',
  '41': 's',
  '42': 's',
  '43': '"',
  '44': ':',
  '45': '"',
  '46': '0',
  '47': 'x',
  '48': 'e',
  '49': '9',
  '50': '4',
  '51': '3',
  '52': '2',
```

Then it eventually gets to
```
[08:11:54.129] [info] Processing 1 logs
[08:11:54.132] [info] new block: 5929534 1531086193
[08:11:54.136] [info] Processing 1 logs
[08:11:54.139] [info] new block: 5929552 1531086425
[08:11:54.142] [info] Processing 1 logs
```

and hangs / stops doing anything

**Comment by joeykrug** [comment]
At the same time my remote geth node gives a write tcp timeout error

**Comment by joeykrug** [comment]
```
Server Error: "Controller mismatch. Configured: 0xb3337164e91b9f05c87c7662c7ac684e8e0ff3e7 Found: 0x0000000000000000000000000000000000000000"
```

too even when it's actually still syncing on a solid node sometimes

**Comment by joeykrug** [comment]
<img width="508" alt="screen shot 2018-07-20 at 9 22 50 am" src="https://user-images.githubusercontent.com/5925937/43013713-a589494a-8bfe-11e8-98e5-e6a4d58aafe6.png">

^ when syncing from localhost

```
[09:16:29.171] [info] new block: 5988510 1531948860
[09:16:29.176] [info] Processing 8 logs
[09:16:34.945] [error] Error: SQLITE_CONSTRAINT: CHECK constraint failed: positiveEndTime

Unhandled rejection Error: SQLITE_CONSTRAINT: CHECK constraint failed: positiveEndTime

```

in console

**Comment by sharkcrayon** [comment]
@joeykrug Are you still getting this issue with 1.0.7? Also, which nodes were you connected to? A lot of people were having syncing issues with Infura about a week ago.

**Comment by sharkcrayon** [comment]
Adding to our internal issue tracker: https://app.clubhouse.io/augur/story/14839/github-augur-app-crashes-when-syncing

**Comment by joeykrug** [comment]
None of these are issues for me anymore
