### ISSUE TITLE
Object has been destroyed

### ISSUE THREAD

**Issue by page1** [AugurProject/augur-app#224]
Just upped to 1.0.5, having more issues than 1.0.4.
Most errors currently log as "Object has been destroyed". Copying a few versions here.

v1
```
[2018-07-22 23:43:16.342] [error] Fatal Error, shutting down servers Error: SQLITE_CONSTRAINT: UNIQUE constraint failed: transfers.transactionHash, transfers.logIndex

[2018-07-22 23:43:16.343] [error] Error: SQLITE_CONSTRAINT: UNIQUE constraint failed: transfers.transactionHash, transfers.logIndex

[2018-07-22 23:43:16.386] [info] Stopping Augur Node Server
[2018-07-22 23:43:16.386] [info] Stopping Augur Node Server
[2018-07-22 23:43:16.388] [error] Error: Object has been destroyed
    at AugurNodeServer.disconnectServerMessage (/Applications/Augur.app/Contents/Resources/app/src/main/augurNodeServer.js:255:17)
    at AugurNodeServer.shutDownServer (/Applications/Augur.app/Contents/Resources/app/src/main/augurNodeServer.js:266:10)
    at BrowserWindow.<anonymous> (/Applications/Augur.app/Contents/Resources/app/src/main/main.js:105:27)
    at emitOne (events.js:116:13)
    at BrowserWindow.emit (events.js:211:7)
    at AugurNodeController._shutdownCallback (/Applications/Augur.app/Contents/Resources/app/node_modules/augur-node/build/controller.js:112:17)
    at processBlockByBlockDetails (/Applications/Augur.app/Contents/Resources/app/node_modules/augur-node/build/blockchain/process-block.js:46:20)
    at process_queue_1.logQueueProcess (/Applications/Augur.app/Contents/Resources/app/node_modules/augur-node/build/blockchain/process-block.js:111:36)
    at /Applications/Augur.app/Contents/Resources/app/node_modules/augur-node/node_modules/async/dist/async.js:473:16
    at iterateeCallback (/Applications/Augur.app/Contents/Resources/app/node_modules/augur-node/node_modules/async/dist/async.js:976:17)
    at /Applications/Augur.app/Contents/Resources/app/node_modules/augur-node/node_modules/async/dist/async.js:958:16
    at logCallback (/Applications/Augur.app/Contents/Resources/app/node_modules/augur-node/build/blockchain/process-queue.js:37:84)
    at db.insert.into.asCallback (/Applications/Augur.app/Contents/Resources/app/node_modules/augur-node/build/blockchain/log-processors/tokens-transferred.js:24:20)
    at tryCatcher (/Applications/Augur.app/Contents/Resources/app/node_modules/bluebird/js/release/util.js:16:23)
    at Promise.errorAdapter [as _rejectionHandler0] (/Applications/Augur.app/Contents/Resources/app/node_modules/bluebird/js/release/nodeify.js:35:34)
    at Promise._settlePromise (/Applications/Augur.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:566:21)

[2018-07-22 23:43:16.400] [info] Stopping Augur UI Server
```

v2
```
[2018-07-22 23:36:34.681] [error] Error: Object has been destroyed
    at AugurNodeServer.disconnectServerMessage (/Applications/Augur.app/Contents/Resources/app/src/main/augurNodeServer.js:255:17)
    at AugurNodeServer.shutDownServer (/Applications/Augur.app/Contents/Resources/app/src/main/augurNodeServer.js:266:10)
    at BrowserWindow.<anonymous> (/Applications/Augur.app/Contents/Resources/app/src/main/main.js:105:27)
    at emitOne (events.js:116:13)
    at BrowserWindow.emit (events.js:211:7)
    at click (/Applications/Augur.app/Contents/Resources/app/src/main/main.js:50:76)
    at MenuItem.click (/Applications/Augur.app/Contents/Resources/electron.asar/browser/api/menu-item.js:55:9)
    at Function.executeCommand (/Applications/Augur.app/Contents/Resources/electron.asar/browser/api/menu.js:29:13)
```

**Comment by bthaile** [comment]
Looks like error from when augur-app is being closed which shutdowns augur-node. Or is something else going on?

**Comment by page1** [comment]
I think I had v1 when trying to sync after being offline for the weekend.
v2 seems to show up much more commonly in my log. I'm not sure of exactly under what condition it shows up.

**Comment by petervecchiarelli** [comment]
https://app.clubhouse.io/augur/story/14478/github-object-has-been-destroyed

**Comment by page1** [comment]
1.0.5 Using the top menu on mac Augur -> Exit after having connected produces this

```
[2018-07-25 10:47:20.860] [info] Stopping Augur Node Server
[2018-07-25 10:47:20.860] [info] Stopping Augur Node Server
[2018-07-25 10:47:20.864] [error] Error: Object has been destroyed
    at AugurNodeServer.disconnectServerMessage (/Applications/Augur.app/Contents/Resources/app/src/main/augurNodeServer.js:255:17)
    at AugurNodeServer.shutDownServer (/Applications/Augur.app/Contents/Resources/app/src/main/augurNodeServer.js:266:10)
    at BrowserWindow.<anonymous> (/Applications/Augur.app/Contents/Resources/app/src/main/main.js:105:27)
    at emitOne (events.js:116:13)
    at BrowserWindow.emit (events.js:211:7)
    at click (/Applications/Augur.app/Contents/Resources/app/src/main/main.js:50:76)
    at MenuItem.click (/Applications/Augur.app/Contents/Resources/electron.asar/browser/api/menu-item.js:55:9)
    at Function.executeCommand (/Applications/Augur.app/Contents/Resources/electron.asar/browser/api/menu.js:29:13)

[2018-07-25 10:47:20.866] [info] Stopping Augur UI Server
```

**Comment by page1** [comment]
Did the same thing in 1.0.6, you just need to let it sync and then Augur -> Exit

**Comment by epheph** [comment]
This seems to have been resolved in https://github.com/AugurProject/augur-app/pull/294 , will go out in next release
