### ISSUE TITLE
Undefined binding

### ISSUE THREAD

**Issue by page1** [AugurProject/augur-app#226]
Tried to dispute a market
```
[2018-07-23 11:45:24.433] [error] getter error:  Error: Undefined binding(s) detected when compiling SELECT query: select `markets`.*, `market_state`.`reportingState` as `reportingState`, `blocks`.`timestamp` as `creationTime` from `markets` left join `market_state` on `markets`.`marketStateId` = `market_state`.`marketStateId` left join `blocks` on `markets`.`creationBlockNumber` = `blocks`.`blockNumber` where `markets`.`marketId` in (?)
    at QueryCompiler_SQLite3.toSQL (/Applications/Augur.app/Contents/Resources/app/node_modules/augur-node/node_modules/knex/lib/query/compiler.js:151:13)
    at Builder.toSQL (/Applications/Augur.app/Contents/Resources/app/node_modules/augur-node/node_modules/knex/lib/query/builder.js:115:44)
    at /Applications/Augur.app/Contents/Resources/app/node_modules/augur-node/node_modules/knex/lib/runner.js:52:32
    at tryCatcher (/Applications/Augur.app/Contents/Resources/app/node_modules/bluebird/js/release/util.js:16:23)
    at /Applications/Augur.app/Contents/Resources/app/node_modules/bluebird/js/release/using.js:185:26
    at tryCatcher (/Applications/Augur.app/Contents/Resources/app/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Applications/Augur.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Applications/Augur.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Applications/Augur.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Applications/Augur.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/Applications/Augur.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:638:18)
    at PromiseArray._resolve (/Applications/Augur.app/Contents/Resources/app/node_modules/bluebird/js/release/promise_array.js:126:19)
    at PromiseArray._promiseFulfilled (/Applications/Augur.app/Contents/Resources/app/node_modules/bluebird/js/release/promise_array.js:144:14)
    at Promise._settlePromise (/Applications/Augur.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:574:26)
    at Promise._settlePromise0 (/Applications/Augur.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Applications/Augur.app/Contents/Resources/app/node_modules/bluebird/js/release/promise.js:693:18)
```

**Comment by pgebheim** [comment]
Hey @page1  -- Thanks for this report I'm looking into it now.

**Comment by pgebheim** [comment]
@page1 

Which version of Augur App were you running? In 1.0.5 we fixed an issue with the dispute page which could be causing this.

**Comment by page1** [comment]
@pgebheim 1.0.5
<img width="126" alt="screen shot 2018-07-23 at 1 01 26 pm" src="https://user-images.githubusercontent.com/6609556/43097199-8820f6f6-8e78-11e8-82ae-eefada3e0391.png">

**Comment by page1** [comment]
At least the dispute page loads in 1.0.5 I'm just not able to send a dispute. It asks me to sign the transaction on the ledger and then no transactions actually show on etherscan.io and this error gets put in the log.

**Comment by bthaile** [comment]
Are you indicating the error above gets put in the logs when you try to dispute a market?

**Comment by page1** [comment]
@bthaile This was my impression. But I can't be 100%
The third time I tried to dispute the transaction made it through.

**Comment by bthaile** [comment]
Do you have an ethernet tx and which market are you disputing?

**Comment by page1** [comment]
I think this is the transaction that worked https://etherscan.io/tx/0x4e8a50183b374610a5b1bd15e681102bb01dbb766bfe28ea17334158fba96870
On this market https://localhost:8080/#/market?id=0x90b60a1b85f0ac1b4606050f5be5c54198f2706c

**Comment by bthaile** [comment]
We had dispute issues that got fixed in 1.0.5, I assume you successfully disputed using 1.0.5. Prior versions would spam augur-node and the UI would allow disputing.

**Comment by page1** [comment]
@bthaile Yes, I attempted to dispute 3 times with 1.0.5 and the third time it worked. Never tried dispute on prior versions.

**Comment by page1** [comment]
We can close this for now if you like. I haven't seen this again (Also haven't tried to dispute anything else) I or someone else can repost if seen again in next dispute round.
