### ISSUE TITLE
Error Cannot GET /

### ISSUE THREAD

**Issue by albatarnik** [AugurProject/augur-app#258]
When I hit "Open Augur App" 
opens this url : 
http://127.0.0.1:8080/#/categories?augur_node=ws%3A%2F%2F127.0.0.1%3A9001&ethereum_node_http=https%3A%2F%2Fmainnet.infura.io%2Faugur&ethereum_node_ws=
I only can see this message 
`Cannot GET /` 

OS: macos high sierra

**Comment by bthaile** [comment]
Do you have another process using port 8080?

If so there should have been an error show up at the bottom of the augur-app interface. 

Also can you look in the log file, it can provide more information. 

Located here: MacOS : ~/Library/Logs/augur/log.log

**Comment by albatarnik** [comment]
Content of log.log file
```

[2018-07-28 15:07:50.042] [info] network name Mainnet
[2018-07-28 15:07:59.273] [info] Starting Augur UI Server
[2018-07-28 15:07:59.274] [info] Looking for certificate files in /Library/Application Support/augur
[2018-07-28 15:08:03.521] [info] Found prior bulk-sync database: /Library/Application Support/augur/augur-1-2.db
[2018-07-28 15:08:03.521] [info] /Library/Application Support/augur/augur-1-2.db
[2018-07-28 15:08:03.593] [info] Sync with blockchain started.
[2018-07-28 15:08:03.596] [info] Getting Augur logs from block 6046548 to block 6046584
[2018-07-28 15:08:04.951] [info] new block: 6046556, 1532800804 (Sat Jul 28 2018 15:00:04 GMT-0300 (-03))
[2018-07-28 15:08:04.974] [info] Processing 1 logs
[2018-07-28 15:08:04.986] [info] new block: 6046568, 1532800956 (Sat Jul 28 2018 15:02:36 GMT-0300 (-03))
[2018-07-28 15:08:04.992] [info] Processing 1 logs
[2018-07-28 15:08:04.999] [info] Finished batch load from 6046548 to 6046584
[2018-07-28 15:08:05.000] [info] Copying bulk sync database to snapshot /Library/Application Support/augur/augur-1-2.db to /Library/Application Support/augur/augur-1-syncing-2.db
[2018-07-28 15:08:05.011] [error] Error: Unable to acquire a connection
    at Client_SQLite3.acquireConnection (/Applications/Augur.app/Contents/Resources/app/node_modules/augur-node/node_modules/knex/lib/client.js:318:40)
    at Runner.ensureConnection (/Applications/Augur.app/Contents/Resources/app/node_modules/augur-node/node_modules/knex/lib/runner.js:227:24)
    at Runner.run (/Applications/Augur.app/Contents/Resources/app/node_modules/augur-node/node_modules/knex/lib/runner.js:47:42)
    at Builder.Target.then (/Applications/Augur.app/Contents/Resources/app/node_modules/augur-node/node_modules/knex/lib/interface.js:35:43)

[2018-07-28 15:08:05.243] [info] /Library/Application Support/augur/augur-1-syncing-2.db
[2018-07-28 15:08:05.244] [info] Sync with blockchain complete.
[2018-07-28 15:08:05.245] [info] Bulk sync with blockchain complete.
[2018-07-28 15:08:05.246] [info] Starting websocket secure server on port 9002
[2018-07-28 15:08:05.250] [info] Starting websocket server on port 9001
[2018-07-28 15:08:06.677] [info] new block: 6046585, 1532801183 (Sat Jul 28 2018 15:06:23 GMT-0300 (-03))
```

**Comment by bthaile** [comment]
Make sure you are on the latest version of augur-app. 

Second try to ‘reset database’ its in the settings menu of augur-app. You will need to do this first thing after starting augur-app before clicking ‘connect’

Also dont use the infura ethereum node endpoint. Grab gethStar or megaGeth

**Comment by albatarnik** [comment]
Okay, I will that, thanks.

**Comment by justinbarry** [comment]
@albatarnik please consider closing this issue if the above steps do not resolve your problem.

**Comment by bthaile** [comment]
not heard from member, closing
