### ISSUE TITLE
Augur 1.3.0 Linux deb throws error and doesn't start up

### ISSUE THREAD

**Issue by bidfish** [AugurProject/augur-app#317]
Augur log file:

`Error: Error: ENOENT: no such file or directory, open '/opt/Augur/resources/app-update.yml'`

**Comment by bthaile** [comment]
We thought we’d lick this. Thanks for reporting. We’ll work it. 

https://app.clubhouse.io/augur/story/15591

**Comment by mrothiel** [comment]
This is how the complete exception looks for me. Also the program still seems to be running, as I have to shut it down with strg+c. Im running Ubuntu 18.04.

`[info] Checking for update
[error] Error: Error: ENOENT: no such file or directory, open '/opt/Augur/resources/app-update.yml'
at /opt/Augur/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:427:27
at Generator.next (<anonymous>)`

`From previous event:
    at AppImageUpdater.loadUpdateConfig (/opt/Augur/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:423:33)
    at Lazy.AppUpdater.configOnDisk (/opt/Augur/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:138:43)
    at Lazy.get value [as value] (/opt/Augur/resources/app.asar/node_modules/lazy-val/src/main.ts:18:23)
    at /opt/Augur/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:339:46`

`From previous event:
    at AppImageUpdater.getUpdateInfo (/opt/Augur/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:335:32)
    at /opt/Augur/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:349:35
    at Generator.next (<anonymous>)`

`From previous event:
    at AppImageUpdater.doCheckForUpdates (/opt/Augur/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:348:34)
    at /opt/Augur/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:287:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)`

`From previous event:
    at AppImageUpdater._checkForUpdates (/opt/Augur/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:282:33)
    at AppImageUpdater.checkForUpdates (/opt/Augur/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:221:35)
    at module.exports (/opt/Augur/resources/app.asar/src/update/check-for-updates.js:73:15)
    at App.app.on (/opt/Augur/resources/app.asar/src/main/main.js:140:3)
    at emitTwo (events.js:131:20)
    at App.emit (events.js:214:7)`

**Comment by bthaile** [comment]
Dup of #317

https://github.com/AugurProject/augur-app/issues/317

Closing

**Comment by bthaile** [comment]
https://github.com/AugurProject/augur-app/releases/tag/v1.3.1

**Comment by bthaile** [comment]
try release 1.3.1, let us know if the issue has been fixed.

**Comment by becin** [comment]
Same issue persists with 1.3.1 using the .deb installer

**Comment by pgebheim** [comment]
Hello @becin!

This issue was fixed in 1.3.2 -- sorry for the inconvenience.
