### ISSUE TITLE
v1.7.0 overwrites `uiPort` setting in `app.config` on start

### ISSUE THREAD

**Issue by veox** [AugurProject/augur-app#401]
... as well as, possibly, the rest of the config file.

By default, `uiPort` is set to `8080`. That port is a "generic" HTTP-alternative, and expecting it to be available is, well, pretentious.

I've changed the port previously to 38080, but after upgrading to `augur-app` v1.7.0 the config file's overwritten with the default, on every app start.

There seems to be no in-app way to change the UI port.

Changing file permissions to read-only results in a hang, with

```
% ./linux-Augur-1.7.0.AppImage                                                                                                                 [opt]
A JavaScript error occurred in the main process
Uncaught Exception:
Error: EACCES: permission denied, open '/home/veox/.augur/app.config'
    at Object.fs.openSync (fs.js:646:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:166:20)
    at Object.fs.writeFileSync (fs.js:1303:33)
    at new JSON (/tmp/.mount_linux-7aIrfz/resources/app.asar/webpack:/src/main/configManager.js:73:30)
    at Object.module.exports.n.app (/tmp/.mount_linux-7aIrfz/resources/app.asar/webpack:/src/main/main.js:83:45)
    at name (/tmp/.mount_linux-7aIrfz/resources/app.asar/webpack:/webpack/bootstrap:37:1)
    at Object.transports (/tmp/.mount_linux-7aIrfz/resources/app.asar/webpack:/src/main/main.js:5:5)
    at name (/tmp/.mount_linux-7aIrfz/resources/app.asar/webpack:/webpack/bootstrap:37:1)
    at /tmp/.mount_linux-7aIrfz/resources/app.asar/webpack:/external "electron-log":1:1
    at Object.<anonymous> (/tmp/.mount_linux-7aIrfz/resources/app.asar/webpack:/external "electron-log":1:1)
    at Object.<anonymous> (/tmp/.mount_linux-7aIrfz/resources/app.asar/main.js:3:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
^C
```

and failure to launch the GUI part of the `electron` application.

**Comment by bthaile** [comment]
We made a recent change that disables users ability to set a custom ui port. We will add a Form textbox in augur-app to make it easier to set a different ui port. 

Look for that feature in the next release.

**Comment by adrake33** [comment]
Closing this since this got implemented yesterday and will be in the next release.
