### ISSUE TITLE
Augur App not updating to latest version

### ISSUE THREAD

**Issue by adrake33** [AugurProject/augur-app#423]
### Summary
I'm running 1.8.3 and attempting to upgrade to 1.8.4. I see the progress bar window open briefly and say 0% for about a second. Then the window closes & Augur App restarts but is not upgraded.

 ### Steps to reproduce
Tell us how to reproduce the issue.
 1. Go to Augur -> Check for Updates
 2. Click button to upgrade.

 ### Expected behavior
Should upgrade to v1.8.4.

 ### Environment
- Operating system: MacOS Mojave

Logs say: 
```
[2018-12-13 09:30:33.730] [info] Starting Augur UI Server
[2018-12-13 09:30:33.736] [info] Found localhost certificate and key
[2018-12-13 09:30:50.165] [info] New version 1.8.4 has been downloaded to /Users/aaron/Library/Application Support/Augur/__update__/mac-Augur-1.8.4.zip
[2018-12-13 09:30:50.169] [info] Stopping Augur UI Server
[2018-12-13 09:30:50.221] [info] / requested
[2018-12-13 09:30:50.227] [info] /app.zip requested
[2018-12-13 09:30:50.227] [info] app.zip requested by Squirrel.Mac, pipe /Users/aaron/Library/Application Support/Augur/__update__/mac-Augur-1.8.4.zip
[2018-12-13 09:30:50.662] [warn] Error: No update available, can't quit and install
    at ProgressBar.close (/Applications/Augur.app/Contents/Resources/app.asar/node_modules/electron-progressbar/source/index.js:171:16)
    at Timeout.setTimeout (/Applications/Augur.app/Contents/Resources/app.asar/node_modules/electron-progressbar/source/index.js:338:26)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
```

[log.log](https://github.com/AugurProject/augur-app/files/2677782/log.log)

**Comment by adrake33** [comment]
Original updaterId (not working): b639c8e7-a160-54b3-b143-04e8e7f872d7
New updaterId (working): 36e729af-c506-5ba9-99ad-d3e128ddd488

**Comment by adrake33** [comment]
@bthaile From what we can tell, this seems to happen if the user downloads a pre-release and then tries to update later (apparently only on a Mac, though).

**Comment by adrake33** [comment]
Closing for now since #693 should hopefully fix this.
