### ISSUE TITLE
[BUG] Positions are missing

### ISSUE THREAD

**Issue by damian-c** [AugurProject/augur-app#451]
### Summary
Positions (filled orders) are missing from the positions page. Only open orders are shown.

### Steps to reproduce
1. Go to Markets, find and fill an open order.
2. Place another order on another market, at a price that won't get filled right away.
3. Close Augur app, and restart it.
4. Go to Portfolio->Positions
5. See that only your open order appears.

### Expected behavior
Shares from filled orders should appear along with open ones, like they did in previous versions.

### Environment
- Operating system: Ubuntu 18.10
- Browser: Firefox

##### If using Augur App:
 - Augur App version: 1.9.0
- Are you connecting with a pre-existing option from the dropdown list of networks?
    - Local Light Node (experimental)

**Comment by damian-c** [comment]
Also in today's 1.10 build from git.

**Comment by adrake33** [comment]
@JohnDanz Can you please investigate this issue?

**Comment by JohnDanz** [comment]
Hey @damian-c,

While looking into this, I filled a bid order by selling 0.001 share on a market. 

Then I navigated to a new market and placed an open order to sell 2 shares at .6 on a market with a midpoint of .31. 

I then navigated to the portfolio>positions page and I see both my open order (on that 2nd market) and the filled order/my current position in the first market.

<img width="1723" alt="screen shot 2019-01-16 at 10 19 08 am" src="https://user-images.githubusercontent.com/10524630/51262664-6dc66800-1978-11e9-8577-8b3472571a8f.png">

This was done with an account that hadn't traded on augur at all before. Is this the same situation you are describing? Did you happen to have any shares already in one of these markets?

**Comment by damian-c** [comment]
Slight correction - I first noticed this when looking on the Positions page for shares I had purchased using a previous version of Augur. 
You are correct - Newly purchased shares do show up under Positions.
However - I found that if I close the app, and then restart it, my newly purchased shares are now missing again.

**Comment by joeykrug** [comment]
https://www.reddit.com/r/Augur/comments/agx0a4/after_upgrading_to_augur_191_the_portfolio_tab/ More different but similar issues

**Comment by joeykrug** [comment]
https://www.reddit.com/r/Augur/comments/agajmw/i_keep_getting_this_error_on_the_augur_web_app/ One more

Let’s be sure all cases are fixed before closing

**Comment by peterjwallin** [comment]
My log file when clicking on Positions tab or calling augur.trading.getUserTradingPositions() API....

[07:54:54.657] [error] getter error:  Error: [BigNumber Error] Not a number: undefined
    at /tmp/.mount_linux-jxxC7B/resources/app.asar/node_modules/augur-node/node_modules/bignumber.js/bignumber.js:1309:27
    at new BigNumber (/tmp/.mount_linux-jxxC7B/resources/app.asar/node_modules/augur-node/node_modules/bignumber.js/bignumber.js:220:67)
    at maxOrMin (/tmp/.mount_linux-jxxC7B/resources/app.asar/node_modules/augur-node/node_modules/bignumber.js/bignumber.js:1220:17)
    at Function.BigNumber.minimum.BigNumber.min (/tmp/.mount_linux-jxxC7B/resources/app.asar/node_modules/augur-node/node_modules/bignumber.js/bignumber.js:586:20)
    at _.chain.mapValues (/tmp/.mount_linux-jxxC7B/resources/app.asar/node_modules/augur-node/src/server/getters/get-user-trading-positions.ts:118:41)
    at /tmp/.mount_linux-jxxC7B/resources/app.asar/node_modules/augur-node/node_modules/lodash/lodash.js:13400:38
    at /tmp/.mount_linux-jxxC7B/resources/app.asar/node_modules/augur-node/node_modules/lodash/lodash.js:4925:15
    at baseForOwn (/tmp/.mount_linux-jxxC7B/resources/app.asar/node_modules/augur-node/node_modules/lodash/lodash.js:3010:24)
    at Function.mapValues (/tmp/.mount_linux-jxxC7B/resources/app.asar/node_modules/augur-node/node_modules/lodash/lodash.js:13399:7)
    at /tmp/.mount_linux-jxxC7B/resources/app.asar/node_modules/augur-node/node_modules/lodash/lodash.js:4388:28
    at arrayReduce (/tmp/.mount_linux-jxxC7B/resources/app.asar/node_modules/augur-node/node_modules/lodash/lodash.js:683:21)
    at baseWrapperValue (/tmp/.mount_linux-jxxC7B/resources/app.asar/node_modules/augur-node/node_modules/lodash/lodash.js:4387:14)
    at LodashWrapper.wrapperValue (/tmp/.mount_linux-jxxC7B/resources/app.asar/node_modules/augur-node/node_modules/lodash/lodash.js:9050:14)
    at /tmp/.mount_linux-jxxC7B/resources/app.asar/node_modules/augur-node/src/server/getters/get-user-trading-positions.ts:132:6
    at Generator.next (<anonymous>)
    at fulfilled (/tmp/.mount_linux-jxxC7B/resources/app.asar/node_modules/augur-node/build/server/getters/get-user-trading-positions.js:4:58)

**Comment by damian-c** [comment]
Seems to be fixed in the current 1.10 build. I can now see all my old positions.

**Comment by bthaile** [comment]
awesome!, closing

**Comment by adrake33** [comment]
Reopening this for now. We should try to confirm that the other users who were seeing this are no longer seeing it once the new version is released.

**Comment by peterjwallin** [comment]
Yes. Issue is resolved. Thanks

**Comment by pgebheim** [comment]
Reddit says problems were resolved in 1.10 as well!

Closing again :-D
