### ISSUE TITLE
Issue Connecting To An Infura Node

### ISSUE THREAD

**Issue by Sm00g15** [AugurProject/augur-app#60]
I keep hitting this error in my terminal
```
[16:12:14.964] [info] Getting Augur logs from block 0 to block 5931130
[16:12:15.472] [info] 
{ Error: ESOCKETTIMEDOUT
    at ClientRequest.<anonymous> (/Users/smagin07/Downloads/augur-app-1.0.0-alpha.23/node_modules/request/request.js:813:19)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at ClientRequest.emit (events.js:208:7)
    at TLSSocket.emitTimeout (_http_client.js:708:34)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at TLSSocket.emit (events.js:208:7)
    at TLSSocket.Socket._onTimeout (net.js:407:8)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
    at Timer.listOnTimeout (timers.js:270:5)
  code: 'ESOCKETTIMEDOUT',
  connect: false,
  data: 
   { id: 8,
     jsonrpc: '2.0',
     method: 'eth_getLogs',
     params: [ [Object] ] } }

```

![screen shot 2018-07-09 at 4 16 07 pm](https://user-images.githubusercontent.com/14209806/42430490-b4ad1500-8393-11e8-8bca-da31ffda6fb5.jpg)

This is also the popup I'm getting. Any ideas what the issue could be?

**Comment by bthaile** [comment]
This issue is we don't have the mainnet contract addresses in the newest version of augur-app. Tomorrow, July 9th we expect the addresses to be added.

**Comment by Sm00g15** [comment]
Ah okay awesome! Looking forward to it!

**Comment by bthaile** [comment]
closing this issue.
