### ISSUE TITLE
Failed to fetch parent block

### ISSUE THREAD

**Issue by karalabe** [AugurProject/augur-app#79]
I've build the app from source, connected to mainnet via Infura. Sync got up to 99%, now just endlessly printing

```
Error: Failed to fetch parent block.
    at Object.<anonymous> (/work/src/github.com/AugurProject/augur-app/node_modules/augur-blockstream/output/source/block-reconciler.js:106:27)
    at step (/work/src/github.com/AugurProject/augur-app/node_modules/augur-blockstream/output/source/block-reconciler.js:32:23)
    at Object.next (/work/src/github.com/AugurProject/augur-app/node_modules/augur-blockstream/output/source/block-reconciler.js:13:53)
    at fulfilled (/work/src/github.com/AugurProject/augur-app/node_modules/augur-blockstream/output/source/block-reconciler.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by karalabe** [comment]
Oh, after a few minutes it passed this.

**Comment by OperationNine** [comment]
I was about to open this exact same issue, it stuck and is now passing. Was using the linux version

**Comment by matthewsedam** [comment]
Same here on mac.

**Comment by petervecchiarelli** [comment]
https://app.clubhouse.io/augur/story/13756/github-failed-to-fetch-parent-block

**Comment by bthaile** [comment]
download version 1.0.3, you shouldn't see this issue anymore.

https://github.com/AugurProject/augur-app/releases

closing
