### ISSUE TITLE
Type Error: Invalid chunk size: 0

### ISSUE THREAD

**Issue by karalabe** [AugurProject/augur-app#80]
```
[14:08:59.200] [error] Fatal Error, shutting down servers TypeError: Invalid chunkSize: 0
    at wrapper.returning._returning (/work/src/github.com/AugurProject/augur-app/node_modules/augur-node/node_modules/knex/lib/util/batchInsert.js:61:21)
    at Promise._execute (/work/src/github.com/AugurProject/augur-app/node_modules/bluebird/js/release/debuggability.js:303:9)
    at Promise._resolveFromExecutor (/work/src/github.com/AugurProject/augur-app/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/work/src/github.com/AugurProject/augur-app/node_modules/bluebird/js/release/promise.js:79:10)
    at batchInsert (/work/src/github.com/AugurProject/augur-app/node_modules/augur-node/node_modules/knex/lib/util/batchInsert.js:57:39)
    at Function.batchInsert (/work/src/github.com/AugurProject/augur-app/node_modules/augur-node/node_modules/knex/lib/util/make-knex.js:68:40)
    at async_1.parallel (/work/src/github.com/AugurProject/augur-app/node_modules/augur-node/build/blockchain/log-processors/market-created.js:111:32)
    at /work/src/github.com/AugurProject/augur-app/node_modules/augur-node/node_modules/async/dist/async.js:3866:24
    at eachOfArrayLike (/work/src/github.com/AugurProject/augur-app/node_modules/augur-node/node_modules/async/dist/async.js:1055:9)
    at eachOf (/work/src/github.com/AugurProject/augur-app/node_modules/augur-node/node_modules/async/dist/async.js:1103:5)
    at _parallel (/work/src/github.com/AugurProject/augur-app/node_modules/augur-node/node_modules/async/dist/async.js:3865:5)
    at Object.parallelLimit [as parallel] (/work/src/github.com/AugurProject/augur-app/node_modules/augur-node/node_modules/async/dist/async.js:3948:5)
    at async_1.forEachOf (/work/src/github.com/AugurProject/augur-app/node_modules/augur-node/build/blockchain/log-processors/market-created.js:106:29)
    at /work/src/github.com/AugurProject/augur-app/node_modules/augur-node/node_modules/async/dist/async.js:473:16
    at eachOfArrayLike (/work/src/github.com/AugurProject/augur-app/node_modules/augur-node/node_modules/async/dist/async.js:1043:9)
    at Object.eachOf (/work/src/github.com/AugurProject/augur-app/node_modules/augur-node/node_modules/async/dist/async.js:1103:5)

[14:08:59.201] [error] TypeError: Invalid chunkSize: 0
    at wrapper.returning._returning (/work/src/github.com/AugurProject/augur-app/node_modules/augur-node/node_modules/knex/lib/util/batchInsert.js:61:21)
    at Promise._execute (/work/src/github.com/AugurProject/augur-app/node_modules/bluebird/js/release/debuggability.js:303:9)
    at Promise._resolveFromExecutor (/work/src/github.com/AugurProject/augur-app/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/work/src/github.com/AugurProject/augur-app/node_modules/bluebird/js/release/promise.js:79:10)
    at batchInsert (/work/src/github.com/AugurProject/augur-app/node_modules/augur-node/node_modules/knex/lib/util/batchInsert.js:57:39)
    at Function.batchInsert (/work/src/github.com/AugurProject/augur-app/node_modules/augur-node/node_modules/knex/lib/util/make-knex.js:68:40)
    at async_1.parallel (/work/src/github.com/AugurProject/augur-app/node_modules/augur-node/build/blockchain/log-processors/market-created.js:111:32)
    at /work/src/github.com/AugurProject/augur-app/node_modules/augur-node/node_modules/async/dist/async.js:3866:24
    at eachOfArrayLike (/work/src/github.com/AugurProject/augur-app/node_modules/augur-node/node_modules/async/dist/async.js:1055:9)
    at eachOf (/work/src/github.com/AugurProject/augur-app/node_modules/augur-node/node_modules/async/dist/async.js:1103:5)
    at _parallel (/work/src/github.com/AugurProject/augur-app/node_modules/augur-node/node_modules/async/dist/async.js:3865:5)
    at Object.parallelLimit [as parallel] (/work/src/github.com/AugurProject/augur-app/node_modules/augur-node/node_modules/async/dist/async.js:3948:5)
    at async_1.forEachOf (/work/src/github.com/AugurProject/augur-app/node_modules/augur-node/build/blockchain/log-processors/market-created.js:106:29)
    at /work/src/github.com/AugurProject/augur-app/node_modules/augur-node/node_modules/async/dist/async.js:473:16
    at eachOfArrayLike (/work/src/github.com/AugurProject/augur-app/node_modules/augur-node/node_modules/async/dist/async.js:1043:9)
    at Object.eachOf (/work/src/github.com/AugurProject/augur-app/node_modules/augur-node/node_modules/async/dist/async.js:1103:5)

[14:08:59.223] [info] Stopping Augur Node Server
[14:08:59.224] [info] Stopping Augur Node Server
[14:08:59.224] [info] Stopping Augur UI Server
[14:08:59.226] [info] Failed to startup: Invalid chunkSize: 0
Unhandled rejection TypeError: Invalid chunkSize: 0
    at wrapper.returning._returning (/work/src/github.com/AugurProject/augur-app/node_modules/augur-node/node_modules/knex/lib/util/batchInsert.js:61:21)
    at Promise._execute (/work/src/github.com/AugurProject/augur-app/node_modules/bluebird/js/release/debuggability.js:303:9)
    at Promise._resolveFromExecutor (/work/src/github.com/AugurProject/augur-app/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/work/src/github.com/AugurProject/augur-app/node_modules/bluebird/js/release/promise.js:79:10)
    at batchInsert (/work/src/github.com/AugurProject/augur-app/node_modules/augur-node/node_modules/knex/lib/util/batchInsert.js:57:39)
    at Function.batchInsert (/work/src/github.com/AugurProject/augur-app/node_modules/augur-node/node_modules/knex/lib/util/make-knex.js:68:40)
    at async_1.parallel (/work/src/github.com/AugurProject/augur-app/node_modules/augur-node/build/blockchain/log-processors/market-created.js:111:32)
    at /work/src/github.com/AugurProject/augur-app/node_modules/augur-node/node_modules/async/dist/async.js:3866:24
    at eachOfArrayLike (/work/src/github.com/AugurProject/augur-app/node_modules/augur-node/node_modules/async/dist/async.js:1055:9)
    at eachOf (/work/src/github.com/AugurProject/augur-app/node_modules/augur-node/node_modules/async/dist/async.js:1103:5)
    at _parallel (/work/src/github.com/AugurProject/augur-app/node_modules/augur-node/node_modules/async/dist/async.js:3865:5)
    at Object.parallelLimit [as parallel] (/work/src/github.com/AugurProject/augur-app/node_modules/augur-node/node_modules/async/dist/async.js:3948:5)
    at async_1.forEachOf (/work/src/github.com/AugurProject/augur-app/node_modules/augur-node/build/blockchain/log-processors/market-created.js:106:29)
    at /work/src/github.com/AugurProject/augur-app/node_modules/augur-node/node_modules/async/dist/async.js:473:16
    at eachOfArrayLike (/work/src/github.com/AugurProject/augur-app/node_modules/augur-node/node_modules/async/dist/async.js:1043:9)
    at Object.eachOf (/work/src/github.com/AugurProject/augur-app/node_modules/augur-node/node_modules/async/dist/async.js:1103:5)

[14:08:59.230] [error] Error: aborted
    at PendingOperation.abort (/work/src/github.com/AugurProject/augur-app/node_modules/tarn/lib/PendingOperation.js:25:17)
    at Promise.all.pendingAcquires.map.acquire (/work/src/github.com/AugurProject/augur-app/node_modules/tarn/lib/Pool.js:190:23)
    at Array.map (<anonymous>)
    at Promise.all.then.then (/work/src/github.com/AugurProject/augur-app/node_modules/tarn/lib/Pool.js:189:34)
    at <anonymous>

(node:1222) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): Error: Object has been destroyed
(node:1222) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
error Command failed with exit code 1.
```

**Comment by ldub** [comment]
Have this same issue on macOS and augur-app 1.0.1

**Comment by petervecchiarelli** [comment]
https://app.clubhouse.io/augur/story/13593/github-type-error-invalid-chunk-size-0

**Comment by justinbarry** [comment]
@ldub @karalabe are you still seeing this issue?

**Comment by sharkcrayon** [comment]
This should be fixed now. I'm going to close this ticket, but please let us know if you see this issue again.
